#!/bin/bash -e

. config.conf

NDK_PATH="$DOWNLOAD_DIR/${NDK_DIR_NAME}"
OPUS_PATH="$DOWNLOAD_DIR/${OPUS_DIR_NAME}"
LIB_PATH="${OPUS_BUILD_OUT_PATH}/libs"
LOG_PATH="${OPUS_BUILD_OUT_PATH}/logs"

LIB_BUILD_PATH="$OPUS_PATH/obj/local"
LIB_HEADERS_PATH="$OPUS_PATH/include"

rm -rf "${OPUS_BUILD_OUT_PATH}"
mkdir -p "${LIB_PATH}"
mkdir -p "${LOG_PATH}"


cd $OPUS_PATH

# Create jni directory and Android.mk
echo "Creating jni directory and Android.mk file in Opus Build directory ..."
mkdir -p jni
cat > jni/Android.mk << 'EOF'
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_PATH := $(LOCAL_PATH)/..

#include the .mk files
include celt_sources.mk
include silk_sources.mk
include opus_sources.mk

MY_MODULE_DIR       := opus

LOCAL_MODULE        := $(MY_MODULE_DIR)

#fixed point sources
SILK_SOURCES += $(SILK_SOURCES_FIXED)

#ARM build
CELT_SOURCES += $(CELT_SOURCES_ARM)
SILK_SOURCES += $(SILK_SOURCES_ARM)

LOCAL_SRC_FILES     := \
    $(CELT_SOURCES) $(SILK_SOURCES) $(OPUS_SOURCES)

LOCAL_LDLIBS        := -lm -llog

LOCAL_C_INCLUDES    := \
$(LOCAL_PATH)/include \
$(LOCAL_PATH)/silk \
$(LOCAL_PATH)/silk/fixed \
$(LOCAL_PATH)/celt

LOCAL_CFLAGS        := -DNULL=0 -DSOCKLEN_T=socklen_t -DLOCALE_NOT_USED -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wno-expansion-to-defined
LOCAL_CFLAGS        += -Drestrict='' -D__EMX__ -DOPUS_BUILD -DFIXED_POINT=1 -DDISABLE_FLOAT_API -DUSE_ALLOCA -DHAVE_LRINT -DHAVE_LRINTF -O3 -fno-math-errno
LOCAL_CPPFLAGS      := -DBSD=1
LOCAL_CPPFLAGS      += -ffast-math -O3 -funroll-loops

include $(BUILD_STATIC_LIBRARY)
EOF

# Build Opus
echo "Building Opus $OPUS_VERSION ..."
$NDK_PATH/ndk-build APP_PLATFORM=android-${TARGET_ANDROID_API} >> "${LOG_PATH}/opus.log" 2>&1

# Copy Files to Build Directory
echo "Copying build file in Opus Build directory ..."
cp -r $LIB_BUILD_PATH/* $LIB_PATH

for arch in "${TARGET_ARCHS[@]}"
do
    echo "Copying Opus file for target arch $arch ..."
    cd $LIB_PATH/$arch
    mkdir -p lib
    mv `ls | grep -w -v lib` lib
    mkdir -p include/opus
    cp $LIB_HEADERS_PATH/* include/opus
done

echo "Finished building Opus"